In [150]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns                      #to check non-linear relation
import sklearn.linear_model as lm          #gives only linear line, no error 
import statsmodels.formula.api as smf      #gives all related to regression
import statsmodels.api as sm
from sklearn.preprocessing import scale 

from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
from sklearn.model_selection import train_test_split, LeaveOneOut, KFold, cross_val_score

from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import RidgeCV, LassoCV
from sklearn import metrics
from sklearn.metrics import mean_squared_error

In [151]:
heart = pd.read_csv("C:/Users/Khusshi Dedhiaa/Desktop/SSDI/heart_disease dataset.csv")
heart2 = heart
heart.head(2)

Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0   63    1       typical     145   233    1        2    150      0      2.3   
1   67    1  asymptomatic     160   286    0        2    108      1      1.5   

   Slope   Ca    Thal  AHD  
0      3  0.0   fixed   No  
1      2  3.0  normal  Yes

In [152]:
heart.isna().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [153]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Age        303 non-null    int64  
 1   Sex        303 non-null    int64  
 2   ChestPain  303 non-null    object 
 3   RestBP     303 non-null    int64  
 4   Chol       303 non-null    int64  
 5   Fbs        303 non-null    int64  
 6   RestECG    303 non-null    int64  
 7   MaxHR      303 non-null    int64  
 8   ExAng      303 non-null    int64  
 9   Oldpeak    303 non-null    float64
 10  Slope      303 non-null    int64  
 11  Ca         299 non-null    float64
 12  Thal       301 non-null    object 
 13  AHD        303 non-null    object 
dtypes: float64(2), int64(9), object(3)
memory usage: 33.3+ KB


### fill na

In [154]:
heart.Ca.unique()

array([ 0.,  3.,  2.,  1., nan])

In [155]:
mode = heart.Ca.mode()[0]
heart.Ca.fillna(mode, inplace=True)

In [156]:
heart.Thal.unique()

array(['fixed', 'normal', 'reversable', nan], dtype=object)

In [157]:
mode = heart.Thal.mode()[0]
heart.Thal.fillna(mode, inplace=True)

In [158]:
heart['Ca'] = heart.Ca.astype(object)

In [159]:
heart.Ca.unique()

array([0.0, 3.0, 2.0, 1.0], dtype=object)

In [160]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Age        303 non-null    int64  
 1   Sex        303 non-null    int64  
 2   ChestPain  303 non-null    object 
 3   RestBP     303 non-null    int64  
 4   Chol       303 non-null    int64  
 5   Fbs        303 non-null    int64  
 6   RestECG    303 non-null    int64  
 7   MaxHR      303 non-null    int64  
 8   ExAng      303 non-null    int64  
 9   Oldpeak    303 non-null    float64
 10  Slope      303 non-null    int64  
 11  Ca         303 non-null    object 
 12  Thal       303 non-null    object 
 13  AHD        303 non-null    object 
dtypes: float64(1), int64(9), object(4)
memory usage: 33.3+ KB


In [161]:
heart.isna().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           0
Thal         0
AHD          0
dtype: int64

### mapping

In [162]:
heart.Thal.unique()

array(['fixed', 'normal', 'reversable'], dtype=object)

In [163]:
heart.ChestPain.unique()

array(['typical', 'asymptomatic', 'nonanginal', 'nontypical'],
      dtype=object)

In [164]:
heart.AHD.unique()

array(['No', 'Yes'], dtype=object)

In [165]:
heart['AHD'] = heart.AHD.map({'No':0, 'Yes':1}) 

In [166]:
heart['Thal'] = heart.Thal.map({'fixed':1, 'normal':2, 'reversable':3})

In [167]:
heart['ChestPain'] = heart.ChestPain.map({'typical':1, 'asymptomatic':2, 'nonanginal':3, 'nontypical':4})

In [168]:
heart.head(2)

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0   63    1          1     145   233    1        2    150      0      2.3   
1   67    1          2     160   286    0        2    108      1      1.5   

   Slope   Ca  Thal  AHD  
0      3  0.0     1    0  
1      2  3.0     2    1

### scaling

In [169]:
heart[['Age','RestBP','Chol','MaxHR','Oldpeak']] = scale(heart[['Age','RestBP','Chol','MaxHR','Oldpeak']],with_mean=True, with_std=True)

In [170]:
heart.head(2)

Age  Sex  ChestPain    RestBP      Chol  Fbs  RestECG     MaxHR  \
0  0.948726    1          1  0.757525 -0.264900    1        2  0.017197   
1  1.392002    1          2  1.611220  0.760415    0        2 -1.821905   

   ExAng   Oldpeak  Slope   Ca  Thal  AHD  
0      0  1.087338      3  0.0     1    0  
1      1  0.397182      2  3.0     2    1

### check vif

In [171]:
x = add_constant(heart)
x = heart[['Age','RestBP','Chol','MaxHR','Oldpeak']]
vif_heart = pd.DataFrame()
vif_heart['feature'] = x.columns
vif_heart['VIF'] = [variance_inflation_factor(x.values,i) for i in range (len(x.columns))]
print(vif_heart)

   feature       VIF
0      Age  1.346502
1   RestBP  1.131893
2     Chol  1.059236
3    MaxHR  1.323332
4  Oldpeak  1.174930


### make model

In [172]:
for i in heart.columns:
    print(i, end='+')

Age+Sex+ChestPain+RestBP+Chol+Fbs+RestECG+MaxHR+ExAng+Oldpeak+Slope+Ca+Thal+AHD+

In [173]:
fit = smf.logit('AHD~Age+Sex+ChestPain+RestBP+Chol+Fbs+RestECG+MaxHR+ExAng+Oldpeak+Slope+Ca+Thal', heart).fit()
fit.summary()

Optimization terminated successfully.
         Current function value: 0.355488
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                    AHD   No. Observations:                  303
Model:                          Logit   Df Residuals:                      287
Method:                           MLE   Df Model:                           15
Date:                Sat, 22 Apr 2023   Pseudo R-squ.:                  0.4846
Time:                        14:51:48   Log-Likelihood:                -107.71
converged:                       True   LL-Null:                       -208.99
Covariance Type:            nonrobust   LLR p-value:                 6.421e-35
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -5.6227      1.240     -4.535      0.000      -8.053      -3.193
Ca[T.1.0]      1.8650      0.455      4.096      0.000       0.973       2.757
Ca[T.2.0]      3.2530      0.675      4.820      0.000       1.930       4.576
Ca[T.3.0]      2.2859      0.805      2.839      0.005       0.708       3.864
Age           -0.2711      0.211     -1.285      0.199      -0.684       0.142
Sex            1.5593      0.447      3.491      0.000       0.684       2.435
ChestPain     -0.2028      0.213     -0.951      0.341      -0.621       0.215
RestBP         0.3760      0.183      2.050      0.040       0.017       0.735
Chol           0.3002      0.190      1.579      0.114      -0.072       0.673
Fbs           -0.6879      0.488     -1.409      0.159      -1.645       0.269
RestECG        0.1914      0.180      1.066      0.287      -0.161       0.543
MaxHR         -0.7034      0.233     -3.019      0.003      -1.160      -0.247
ExAng          1.3195      0.393      3.357      0.001       0.549       2.090
Oldpeak        0.2285      0.243      0.939      0.348      -0.249       0.706
Slope          0.7115      0.358      1.990      0.047       0.011       1.412
Thal           0.9924      0.296      3.348      0.001       0.411       1.573
==============================================================================
"""

In [174]:
fit1 = smf.logit('AHD~Sex+RestBP+MaxHR+ExAng+Slope+Ca+Thal', heart).fit()
fit1.summary()

Optimization terminated successfully.
         Current function value: 0.373137
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                    AHD   No. Observations:                  303
Model:                          Logit   Df Residuals:                      293
Method:                           MLE   Df Model:                            9
Date:                Sat, 22 Apr 2023   Pseudo R-squ.:                  0.4590
Time:                        14:51:49   Log-Likelihood:                -113.06
converged:                       True   LL-Null:                       -208.99
Covariance Type:            nonrobust   LLR p-value:                 1.679e-36
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -6.4576      0.930     -6.945      0.000      -8.280      -4.635
Ca[T.1.0]      1.6902      0.424      3.985      0.000       0.859       2.521
Ca[T.2.0]      3.0998      0.581      5.338      0.000       1.962       4.238
Ca[T.3.0]      2.2357      0.735      3.042      0.002       0.795       3.676
Sex            1.4605      0.399      3.662      0.000       0.679       2.242
RestBP         0.3458      0.167      2.068      0.039       0.018       0.674
MaxHR         -0.6439      0.204     -3.154      0.002      -1.044      -0.244
ExAng          1.4343      0.376      3.814      0.000       0.697       2.171
Slope          0.8861      0.281      3.156      0.002       0.336       1.436
Thal           1.0702      0.283      3.776      0.000       0.515       1.626
==============================================================================
"""

In [175]:
heart

Age  Sex  ChestPain    RestBP      Chol  Fbs  RestECG     MaxHR  \
0    0.948726    1          1  0.757525 -0.264900    1        2  0.017197   
1    1.392002    1          2  1.611220  0.760415    0        2 -1.821905   
2    1.392002    1          2 -0.665300 -0.342283    0        2 -0.902354   
3   -1.932564    1          3 -0.096170  0.063974    0        0  1.637359   
4   -1.489288    0          4 -0.096170 -0.825922    0        2  0.980537   
..        ...  ...        ...       ...       ...  ...      ...       ...   
298 -1.046013    1          1 -1.234430  0.334813    0        0 -0.770990   
299  1.502821    1          2  0.700612 -1.038723    1        0 -0.376896   
300  0.283813    1          2 -0.096170 -2.238149    0        0 -1.515388   
301  0.283813    0          4 -0.096170 -0.206864    0        2  1.068113   
302 -1.821745    1          3  0.359134 -1.386944    0        0  1.024325   

     ExAng   Oldpeak  Slope   Ca  Thal  AHD  
0        0  1.087338      3  0.0     1    0  
1        1  0.397182      2  3.0     2    1  
2        1  1.346147      2  2.0     3    1  
3        0  2.122573      3  0.0     2    0  
4        0  0.310912      1  0.0     2    0  
..     ...       ...    ...  ...   ...  ...  
298      0  0.138373      2  0.0     3    1  
299      0  2.036303      2  2.0     3    1  
300      1  0.138373      2  1.0     3    1  
301      0 -0.896862      2  1.0     2    1  
302      0 -0.896862      1  0.0     2    0  

[303 rows x 14 columns]

In [176]:
heart = pd.get_dummies(heart, columns=['Sex','ExAng','Slope','Ca','Thal'])

C:\Users\Khusshi Dedhiaa\AppData\Local\Temp\ipykernel_54408\1685931590.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  heart = pd.get_dummies(heart, columns=['Sex','ExAng','Slope','Ca','Thal'])


In [177]:
heart.head(2)

Age  ChestPain    RestBP      Chol  Fbs  RestECG     MaxHR   Oldpeak  \
0  0.948726          1  0.757525 -0.264900    1        2  0.017197  1.087338   
1  1.392002          2  1.611220  0.760415    0        2 -1.821905  0.397182   

   AHD  Sex_0  ...  Slope_1  Slope_2  Slope_3  Ca_0.0  Ca_1.0  Ca_2.0  Ca_3.0  \
0    0      0  ...        0        0        1       1       0       0       0   
1    1      0  ...        0        1        0       0       0       0       1   

   Thal_1  Thal_2  Thal_3  
0       1       0       0  
1       0       1       0  

[2 rows x 23 columns]

In [178]:
heart.columns

Index(['Age', 'ChestPain', 'RestBP', 'Chol', 'Fbs', 'RestECG', 'MaxHR',
       'Oldpeak', 'AHD', 'Sex_0', 'Sex_1', 'ExAng_0', 'ExAng_1', 'Slope_1',
       'Slope_2', 'Slope_3', 'Ca_0.0', 'Ca_1.0', 'Ca_2.0', 'Ca_3.0', 'Thal_1',
       'Thal_2', 'Thal_3'],
      dtype='object')

### confusion matrix

In [179]:
actual = heart.AHD
x = heart2[['Sex','RestBP','MaxHR','ExAng','Slope','Ca','Thal']]
predicted = round(fit1.predict(x))
confusion_matrix = metrics.confusion_matrix(actual,predicted)

In [180]:
confusion_matrix

array([[143,  21],
       [ 27, 112]], dtype=int64)

#### confusion matrix = [TP   FP],
#### .................................[FN   TN]

#### accuracy = (TP + TN) / total

In [181]:
#total 
len(heart2)

303

In [182]:
accuracy = (143+112)/303
accuracy

0.8415841584158416

In [183]:
Y = heart.AHD
X = heart2[['Sex','RestBP','MaxHR','ExAng','Slope','Ca','Thal']]

In [184]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

In [185]:
y_test

204    0
159    0
219    0
174    1
184    1
      ..
0      0
288    0
259    1
179    0
110    1
Name: AHD, Length: 61, dtype: int64

In [186]:
lreg_model = lm.LogisticRegression()
lreg_model.fit(x_train,y_train)

LogisticRegression()

In [187]:
actual1 = y_test
predicted1 = round(fit1.predict(x_test))
confusion_matrix1 = metrics.confusion_matrix(actual1,predicted1)

In [188]:
confusion_matrix1

array([[29,  5],
       [ 6, 21]], dtype=int64)

In [189]:
len(y_test)

61

In [190]:
accuracy1 = (29+21)/61
accuracy1

0.819672131147541

In [191]:
kfold = KFold(n_splits=10)          
test = cross_val_score(lreg_model,X,Y,cv = kfold, scoring='accuracy', n_jobs=-1)    #this accuracy is not same as above accuracy
print(np.mean(test))

0.8316129032258065
